[package]
name = "fq_data_broker"
version = "0.1.0"
edition = "2021"

[dependencies]
ibapi = "0.4.2"
ibapi_handler = {path = "../ibapi_handler" }
range_data_storage = {path = "../range_data_storage" }
ordered-float = "4.2.0"